# Generated by Django 3.2.7 on 2021-12-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_followuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuser',
            name='follow',
            field=models.BooleanField(default=False),
        ),
    ]
